"""
CV Module 6 – Motion tracking validation script.

This script provides an interactive way to validate theoretical motion
tracking equations using both manual pixel selection and dense optical
flow. For two consecutive frames from each of two videos, the user
clicks corresponding pixel locations. The script:

1. Records the clicked pixel coordinates in each frame.
2. Computes the manual displacement \((dx, dy)\) between frames.
3. Computes dense optical flow and reads the flow vector at the clicked
   location to compare with the manual displacement.

Usage:
    python tracking_validation.py

Workflow:
- Ensure the four input images
  (`images_and_videos/video1_frame125.png`,
   `images_and_videos/video1_frame126.png`,
   `images_and_videos/video2_frame95.png`,
   `images_and_videos/video2_frame96.png`)
  exist (for example, generated by `frame.py`).
- A window will open for each image; click a single point of interest
  in each image and press any key to advance to the next one.
- After all four clicks, the script prints manual displacements and
  the corresponding optical-flow vectors for both videos.
"""

import cv2
import numpy as np

images = [
    "images_and_videos/video1_frame125.png",
    "images_and_videos/video1_frame126.png",
    "images_and_videos/video2_frame95.png",
    "images_and_videos/video2_frame96.png",
]

coords = []
current_image = ""


def click(event, x, y, flags, param):
    """Mouse callback to record pixel coordinates on left button click."""
    global coords
    if event == cv2.EVENT_LBUTTONDOWN:
        print("Image:", param)
        print("Pixel coordinate:", x, y)
        print("----------------------")
        coords.append((x, y))

for img_name in images:

    img = cv2.imread(img_name)

    cv2.imshow("image", img)
    cv2.setMouseCallback("image", click, img_name)

    print("Click a point on:", img_name)
    print("Press any key for next image")

    cv2.waitKey(0)

cv2.destroyAllWindows()

# -----------------------------
# Manual displacement (dx, dy)
# -----------------------------

print("\n===== Manual Displacement =====")

x1, y1 = coords[0]
x2, y2 = coords[1]

dx1 = x2 - x1
dy1 = y2 - y1

print("Video1:")
print("Frame125:", (x1, y1))
print("Frame126:", (x2, y2))
print("dx =", dx1, "dy =", dy1)

x3, y3 = coords[2]
x4, y4 = coords[3]

dx2 = x4 - x3
dy2 = y4 - y3

print("\nVideo2:")
print("Frame95:", (x3, y3))
print("Frame96:", (x4, y4))
print("dx =", dx2, "dy =", dy2)

# -----------------------------
# Optical flow-based validation
# -----------------------------

print("\n===== Optical Flow Validation =====")

# Video1: compute optical flow between frame 125 and 126
frame1 = cv2.imread("images_and_videos/video1_frame125.png")
frame2 = cv2.imread("images_and_videos/video1_frame126.png")

g1 = cv2.cvtColor(frame1, cv2.COLOR_BGR2GRAY)
g2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

flow = cv2.calcOpticalFlowFarneback(
    g1,
    g2,
    None,
    0.5,
    3,
    15,
    3,
    5,
    1.2,
    0,
)

u, v = flow[y1, x1]

print("\nVideo1 Optical Flow:", u, v)

# Video2: compute optical flow between frame 95 and 96
frame3 = cv2.imread("images_and_videos/video2_frame95.png")
frame4 = cv2.imread("images_and_videos/video2_frame96.png")

g3 = cv2.cvtColor(frame3, cv2.COLOR_BGR2GRAY)
g4 = cv2.cvtColor(frame4, cv2.COLOR_BGR2GRAY)

flow2 = cv2.calcOpticalFlowFarneback(
    g3,
    g4,
    None,
    0.5,
    3,
    15,
    3,
    5,
    1.2,
    0,
)

u2, v2 = flow2[y3, x3]

print("Video2 Optical Flow:", u2, v2)